server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ReviewSpring?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnection=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver