server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service  # NOTE: 회원가입
          uri: lb://user-service
          predicates:
            - Path=/user/sign-up
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: user-service  # NOTE: 로그인
          uri: lb://user-service
          predicates:
            - Path=/user/sign-in
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: user-service  # NOTE: 그 외
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
            - name: AuthorizationFilter
              args:
                baseMessage: Unauthorized
        #            - name: Retry
        #              args:
        #                retries: 3
        #                statuses: INTERNAL_SERVER_ERROR
        #                methods: GET, POST