today = input('요일: ')
month = input('월: ')
day = input('일: ')
min_temperature = input('최저 기온: ')
max_temperature = input('최저 기온: ')
precipitation = input('비올 확률: ')
dust_concentration = input('미세먼지 농도: ')
sunrise_hour = input('일출 시간(시): ')
sunrise_minute = input('일출 시간(분): ')
sunset_hour = input('일몰 시간(시)')
sunset_minute = input('일몰 시간(분)')

print('내일 날씨 예보입니다.')
print(f'{today}요일인 {month}월 {day}일, 최저 기온은 {min_temperature}, 최고 기온은 {max_temperature}로 예상됩니다.')
print(f'비올 확률은 {precipitation}이고, 미세먼지 수준은 {dust_concentration}입니다.')
print(f'일출 시간은 오전 {sunrise_hour}시 {sunrise_minute}분, 일몰 시간은 오후 {sunset_hour}시 {sunset_minute}분입니다.')
print(f'지금까지 {month}월 {day}일 {today}요일, 날씨 예보였습니다.')