server:
  port: 8100

zuul:
  routes:
    member-server:
      path: /member/**
      serviceId: member-server
    todo-server:
      path: /todo/**
      serviceId: todo-server
    auth-server:
      path: /auth/**
      serviceId: auth-server

spring:
  application:
    name: zuul-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka