server:
  port: 8200

spring:
  application:
    name: auth-service-1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth-secret
    resource:
      jwt:
        key-value: jwt_secret_key
