[package]
name = "rust_study_project"
version = "0.1.0"
authors = ["CJW-MAPU <c.j.biz.woong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.6.1"